/* Bewerk hier de teksten, shows, contactgegevens en het repertoire. */
window.ROCKTIFIED_CONTENT = {
  contactEmail: 'rocktified@hotmail.com',
  aboutIntro: '					Rocktified is een coverband uit de omgeving van Zundert met een sterke live-reputatie en al 16 jaar een vaste waarde op verschillende podia en feesten. De huidige bezetting bestaat uit Demi (zang), Bart (gitaar), Ed (bas) en Dave (drums) – een hechte groep muzikanten die met zichtbaar plezier samen speelt. Met een repertoire vol rockklassiekers en herkenbare hits uit de jaren ’80 en ’90 zorgt Rocktified voor een energieke, toegankelijke show waar het publiek makkelijk in mee kan. Geen ingewikkeld gedoe, gewoon goede muziek, gespeeld met overtuiging en chemie op het podium.',
  shows: [
    { day: '3', month: 'OCT', weekday: 'ZATERDAG', title: 'Fancy fair', location: 'Koutershof, Rijsbergen', type: 'Gratis' },
    { day: '11', month: 'SEP', weekday: 'VRIJDAG', title: 'Bandjes & Borrels', location: 'Baanhof, Wouw', type: 'Afgelopen' },
    { day: '15', month: 'AUG', weekday: 'ZATERDAG', title: 'Besloten evenement', location: 'Besloten', type: 'Afgelopen' },
    { day: '5', month: 'AUG', weekday: 'WOENSDG', title: 'JAXtival', location: 'Cafe JAX Roosendaal', type: 'Afgelopen' }
  ],
  repertoire: [
    { artist: 'AC/DC', song: 'Highway to Hell' },
    { artist: 'AC/DC', song: 'Whole Lotta Rosie' },
    { artist: "Guns N' Roses", song: "Sweet Child O' Mine" },
    { artist: 'Golden Earring', song: 'Radar love' },
    { artist: "Bryan Adams", song: 'Run to you' },
    { artist: 'Queen', song: 'A kind of magic' },
    { artist: 'The White Stripes', song: 'Seven Nation Army' },
    { artist: 'Robbie Williams', song: 'Angels' },
    { artist: 'The Cranberries', song: 'Zombie' },
    { artist: 'Steppenwolf', song: 'Born to Be Wild' },
    { artist: 'Cheap Trick', song: 'I Want You to Want Me' },
    { artist: 'Joan Jett & the Blackhearts', song: "I Love Rock 'n Roll" },
    { artist: 'The Rolling Stones', song: "Satisfaction" },
    { artist: 'De Dijk', song: 'Ik kan het niet alleen' },
    { artist: 'The Proclaimers', song: "500 Miles" },
    { artist: 'Shocking Blue', song: 'Venus' },
    { artist: 'Blur', song: 'Song 2' },
    { artist: 'Jet', song: 'Are You Gonna Be My Girl' },
    { artist: 'Kelly Clarkson', song: 'Behind These Hazel Eyes' },
    { artist: 'The Fratellis', song: 'Chelsea Dagger' },
    { artist: 'CCR', song: 'Bad Moon Rising' },
    { artist: 'Baseballs', song: 'Umbrella' },
    { artist: 'Status Quo', song: 'Whatever You Want' },
    { artist: 'Green Day', song: 'Holiday' },
    { artist: 'ABBA', song: 'Does Your Mother Know' },
    { artist: 'Nirvana', song: 'Smells Like Teen Spirit' },
    { artist: 'Blondie', song: 'One Way or Another' },
    { artist: 'The Romantics', song: 'What I Like About You' },
    { artist: 'Muse', song: 'Psycho' },
    { artist: 'Metallica', song: 'Enter Sandman' },
    { artist: 'Pearl Jam', song: 'Jeremy' },
    { artist: 'De Kreuners', song: 'Ik wil je' },
    { artist: 'Franz Ferdinand', song: 'Take Me Out' }
  ]
};
